version: "3.9"
services:
    web:
        build: .
        environment:
            - ASPNETCORE_ENVIRONMENT="Production"
            - ASPNETCORE_URLS=http://*:80;
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
            # - ASPNETCORE_URLS=https://*:443;http://*:80;
            # - ASPNETCORE_HTTPS_PORT=8001
        ports:
            - "8000:80"
            # - "8001:443"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "QnADemoP@ssw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"